#InterNova Data Analytics Internship


In [29]:
"""
NumPy & Pandas Assignment - Complete Solution
Author: Data Analytics Student
Date: 2026

This script demonstrates practical skills in NumPy and Pandas for Data Analytics.
"""

'\nNumPy & Pandas Assignment - Complete Solution\nAuthor: Data Analytics Student\nDate: 2026\n\nThis script demonstrates practical skills in NumPy and Pandas for Data Analytics.\n'

In [30]:
import numpy as np
import pandas as pd
import os

In [31]:
# Task 1: NumPy Introduction & Arrays....

print("=" * 80)
print("TASK 1: NumPy Introduction & Arrays")
print("=" * 80)

# Create a NumPy array containing at least 10 numbers
arr1 = np.array([5, 12, 18, 23, 27, 34, 41, 45, 52, 58, 63, 67])

# Display the array
print("Array:", arr1)

# Display the array's shape, size, and data type
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)

# Create a one-dimensional array
one_d = np.array([1, 2, 3, 4, 5])
print("\nOne-dimensional array:", one_d)

# Create a two-dimensional array
two_d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Two-dimensional array:\n", two_d)

TASK 1: NumPy Introduction & Arrays
Array: [ 5 12 18 23 27 34 41 45 52 58 63 67]
Shape: (12,)
Size: 12
Data Type: int64

One-dimensional array: [1 2 3 4 5]
Two-dimensional array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
# Task 2: NumPy Indexing, Slicing & Reshaping

print("\n" + "=" * 80)
print("TASK 2: NumPy Indexing, Slicing & Reshaping")
print("=" * 80)

# Create a NumPy array
arr2 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:", arr2)

# Access specific elements using indexing
print("\nElement at index 0:", arr2[0])
print("Element at index 5:", arr2[5])
print("Element at index -1:", arr2[-1])

# Extract a portion of the array using slicing
print("\nSlice [2:6]:", arr2[2:6])
print("Slice [3:]:", arr2[3:])
print("Slice [:5]:", arr2[:5])
print("Slice [::2]:", arr2[::2])

# Create a two-dimensional array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print("\nTwo-dimensional array:\n", arr_2d)

# Access specific rows and columns
print("\nRow 1:", arr_2d[1])
print("Column 2:", arr_2d[:, 2])
print("Element at [2, 3]:", arr_2d[2, 3])
print("Subarray [1:3, 1:3]:\n", arr_2d[1:3, 1:3])

# Reshape an array into different dimensions
arr_reshape = np.arange(1, 13)
print("\nOriginal array:", arr_reshape)
print("Original shape:", arr_reshape.shape)

reshaped_3x4 = arr_reshape.reshape(3, 4)
print("\nReshaped to 3x4:\n", reshaped_3x4)

reshaped_2x6 = arr_reshape.reshape(2, 6)
print("\nReshaped to 2x6:\n", reshaped_2x6)

reshaped_2x2x3 = arr_reshape.reshape(2, 2, 3)
print("\nReshaped to 2x2x3:\n", reshaped_2x2x3)


TASK 2: NumPy Indexing, Slicing & Reshaping
Original array: [ 10  20  30  40  50  60  70  80  90 100]

Element at index 0: 10
Element at index 5: 60
Element at index -1: 100

Slice [2:6]: [30 40 50 60]
Slice [3:]: [ 40  50  60  70  80  90 100]
Slice [:5]: [10 20 30 40 50]
Slice [::2]: [10 30 50 70 90]

Two-dimensional array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row 1: [5 6 7 8]
Column 2: [ 3  7 11 15]
Element at [2, 3]: 12
Subarray [1:3, 1:3]:
 [[ 6  7]
 [10 11]]

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original shape: (12,)

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped to 2x2x3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [33]:
# Task 3: NumPy Mathematical & Statistical Operations

print("\n" + "=" * 80)
print("TASK 3: NumPy Mathematical & Statistical Operations")
print("=" * 80)

# Create a numerical dataset
data = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95, 105])
print("Dataset:", data)

# Mathematical Operations
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 6, 8])

print("\nMathematical Operations:")
print("Array a:", a)
print("Array b:", b)
print("Addition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (a / b):", a / b)

# Statistical Functions
print("\nStatistical Functions:")
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Standard Deviation:", np.std(data))
print("Sum:", np.sum(data))


TASK 3: NumPy Mathematical & Statistical Operations
Dataset: [ 15  25  35  45  55  65  75  85  95 105]

Mathematical Operations:
Array a: [10 20 30 40]
Array b: [2 4 6 8]
Addition (a + b): [12 24 36 48]
Subtraction (a - b): [ 8 16 24 32]
Multiplication (a * b): [ 20  80 180 320]
Division (a / b): [5. 5. 5. 5.]

Statistical Functions:
Mean: 60.0
Median: 60.0
Minimum: 15
Maximum: 105
Standard Deviation: 28.722813232690143
Sum: 600


In [34]:
# Task 4: Pandas Series & DataFrame (10 Marks)

print("\n" + "=" * 80)
print("TASK 4: Pandas Series & DataFrame")
print("=" * 80)

# Create a Pandas Series
series = pd.Series([85, 92, 78, 90, 88], index=['Math', 'Physics', 'Chemistry', 'Biology', 'English'])
print("Pandas Series (Student Marks):")
print(series)

# Create a DataFrame containing student information
df_students = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [20, 21, 19, 22, 20],
    'Marks': [85, 92, 78, 90, 88],
    'Grade': ['B', 'A', 'C', 'A', 'B']
})

print("\nDataFrame (Student Information):")
print(df_students)

# Display the column names
print("\nColumn Names:", df_students.columns.tolist())

# Display the index
print("Index:", df_students.index.tolist())

# Add a new column to the DataFrame
df_students['Status'] = ['Pass', 'Pass', 'Pass', 'Pass', 'Pass']
print("\nUpdated DataFrame (with Status column):")
print(df_students)


TASK 4: Pandas Series & DataFrame
Pandas Series (Student Marks):
Math         85
Physics      92
Chemistry    78
Biology      90
English      88
dtype: int64

DataFrame (Student Information):
   Student_ID     Name  Age  Marks Grade
0         101    Alice   20     85     B
1         102      Bob   21     92     A
2         103  Charlie   19     78     C
3         104    Diana   22     90     A
4         105      Eve   20     88     B

Column Names: ['Student_ID', 'Name', 'Age', 'Marks', 'Grade']
Index: [0, 1, 2, 3, 4]

Updated DataFrame (with Status column):
   Student_ID     Name  Age  Marks Grade Status
0         101    Alice   20     85     B   Pass
1         102      Bob   21     92     A   Pass
2         103  Charlie   19     78     C   Pass
3         104    Diana   22     90     A   Pass
4         105      Eve   20     88     B   Pass


In [35]:
# Task 5: Reading & Inspecting Data (10 Marks)

print("\n" + "=" * 80)
print("TASK 5: Reading & Inspecting Data")
print("=" * 80)

# Create a sample CSV file for demonstration
sample_data = {
    'Product_ID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones',
                     'Webcam', 'USB Hub', 'Speaker', 'Microphone', 'Charger'],
    'Category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Electronics',
                 'Accessories', 'Accessories', 'Electronics', 'Electronics', 'Accessories'],
    'Price': [75000, 1200, 3500, 15000, 4500, 2800, 1500, 6000, 3200, 1800],
    'Stock': [50, 200, 150, 75, 120, 90, 180, 60, 85, 220],
    'Rating': [4.5, 4.2, 3.8, 4.6, 4.3, 3.9, 4.1, 4.4, 4.0, 3.7]
}

df_sample = pd.DataFrame(sample_data)
df_sample.to_csv('sample_products.csv', index=False)
print("Created sample CSV file: sample_products.csv")

# Read the CSV file using Pandas
df = pd.read_csv('sample_products.csv')

# Display the first 5 rows using head()
print("\nFirst 5 rows (head()):")
print(df.head())

# Display the last 5 rows using tail()
print("\nLast 5 rows (tail()):")
print(df.tail())

# Check the number of rows and columns
print("\nShape (rows, columns):", df.shape)
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

# Display column names
print("\nColumn Names:", df.columns.tolist())

# Check data types using dtypes
print("\nData Types:")
print(df.dtypes)

# Use info() and describe() to understand the dataset
print("\nDataset Info:")
print(df.info())

print("\nDataset Description (describe()):")
print(df.describe())



TASK 5: Reading & Inspecting Data
Created sample CSV file: sample_products.csv

First 5 rows (head()):
   Product_ID Product_Name     Category  Price  Stock  Rating
0        1001       Laptop  Electronics  75000     50     4.5
1        1002        Mouse  Accessories   1200    200     4.2
2        1003     Keyboard  Accessories   3500    150     3.8
3        1004      Monitor  Electronics  15000     75     4.6
4        1005   Headphones  Electronics   4500    120     4.3

Last 5 rows (tail()):
   Product_ID Product_Name     Category  Price  Stock  Rating
5        1006       Webcam  Accessories   2800     90     3.9
6        1007      USB Hub  Accessories   1500    180     4.1
7        1008      Speaker  Electronics   6000     60     4.4
8        1009   Microphone  Electronics   3200     85     4.0
9        1010      Charger  Accessories   1800    220     3.7

Shape (rows, columns): (10, 6)
Number of rows: 10
Number of columns: 6

Column Names: ['Product_ID', 'Product_Name', 'Category',

In [36]:
# Task 6: Selecting, Filtering & Sorting Data (10 Marks)


print("\n" + "=" * 80)
print("TASK 6: Selecting, Filtering & Sorting Data")
print("=" * 80)

# Select specific columns
print("\nSelect specific columns (Product_Name, Price, Rating):")
print(df[['Product_Name', 'Price', 'Rating']])

# Select specific rows
print("\nSelect specific rows (0, 2, 4):")
print(df.iloc[[0, 2, 4]])

# Filter records based on a condition
print("\nFilter: Products with Price > 5000:")
print(df[df['Price'] > 5000])

# Apply multiple filtering conditions
print("\nFilter: Electronics with Rating >= 4.3:")
print(df[(df['Category'] == 'Electronics') & (df['Rating'] >= 4.3)])

# Sort data in ascending order
print("\nSort by Price (Ascending):")
print(df.sort_values('Price', ascending=True))

# Sort data in descending order
print("\nSort by Rating (Descending):")
print(df.sort_values('Rating', ascending=False))



TASK 6: Selecting, Filtering & Sorting Data

Select specific columns (Product_Name, Price, Rating):
  Product_Name  Price  Rating
0       Laptop  75000     4.5
1        Mouse   1200     4.2
2     Keyboard   3500     3.8
3      Monitor  15000     4.6
4   Headphones   4500     4.3
5       Webcam   2800     3.9
6      USB Hub   1500     4.1
7      Speaker   6000     4.4
8   Microphone   3200     4.0
9      Charger   1800     3.7

Select specific rows (0, 2, 4):
   Product_ID Product_Name     Category  Price  Stock  Rating
0        1001       Laptop  Electronics  75000     50     4.5
2        1003     Keyboard  Accessories   3500    150     3.8
4        1005   Headphones  Electronics   4500    120     4.3

Filter: Products with Price > 5000:
   Product_ID Product_Name     Category  Price  Stock  Rating
0        1001       Laptop  Electronics  75000     50     4.5
3        1004      Monitor  Electronics  15000     75     4.6
7        1008      Speaker  Electronics   6000     60     4.4

Fi

In [37]:
# Task 7: Handling Missing Values (10 Marks)

print("\n" + "=" * 80)
print("TASK 7: Handling Missing Values")
print("=" * 80)

# Create a dataset with missing values
data_missing = {
    'Student_ID': [1, 2, 3, 4, 5, 6, 7],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank', 'Grace'],
    'Math': [85, 92, np.nan, 90, 88, 76, 95],
    'Physics': [78, np.nan, 85, 92, np.nan, 88, 90],
    'Chemistry': [90, 88, 75, np.nan, 82, 95, 88],
    'Attendance': [95, 88, 92, 85, np.nan, 90, 87]
}

df_missing = pd.DataFrame(data_missing)

print("\nDataset with Missing Values:")
print(df_missing)

# Identify missing values using isnull() / isna()
print("\nMissing Values (isnull()):")
print(df_missing.isnull())

# Count missing values in each column
print("\nMissing Values Count per Column:")
print(df_missing.isnull().sum())

# Remove rows containing missing values
df_dropped = df_missing.dropna()
print("\nDataset after dropping rows with missing values:")
print(df_dropped)

# Fill missing values using appropriate methods
df_filled = df_missing.copy()
df_filled['Math'] = df_filled['Math'].fillna(df_filled['Math'].mean())
df_filled['Physics'] = df_filled['Physics'].fillna(df_filled['Physics'].median())
df_filled['Chemistry'] = df_filled['Chemistry'].fillna(0)  # Fill with 0
df_filled['Attendance'] = df_filled['Attendance'].fillna(df_filled['Attendance'].mode()[0])

print("\nDataset after filling missing values:")
print(df_filled)

print("\n" + "-" * 80)
print("Why handling missing data is important in Data Analytics:")
print("-" * 80)
print("""
1. Data Quality: Missing values can lead to biased or inaccurate analysis results.
2. Statistical Validity: Many statistical methods require complete datasets to produce valid results.
3. Machine Learning: Most ML algorithms cannot handle missing values and will fail or produce poor results.
4. Decision Making: Incomplete data can lead to incorrect business decisions and insights.
5. Data Integrity: Handling missing values properly maintains the integrity and reliability of your analysis.
6. Pattern Recognition: Understanding why data is missing can reveal important patterns about data collection.
""")


TASK 7: Handling Missing Values

Dataset with Missing Values:
   Student_ID     Name  Math  Physics  Chemistry  Attendance
0           1    Alice  85.0     78.0       90.0        95.0
1           2      Bob  92.0      NaN       88.0        88.0
2           3  Charlie   NaN     85.0       75.0        92.0
3           4    Diana  90.0     92.0        NaN        85.0
4           5      Eve  88.0      NaN       82.0         NaN
5           6    Frank  76.0     88.0       95.0        90.0
6           7    Grace  95.0     90.0       88.0        87.0

Missing Values (isnull()):
   Student_ID   Name   Math  Physics  Chemistry  Attendance
0       False  False  False    False      False       False
1       False  False  False     True      False       False
2       False  False   True    False      False       False
3       False  False  False    False       True       False
4       False  False  False     True      False        True
5       False  False  False    False      False       False
6

In [38]:
# Task 8: Merge, Concatenate, GroupBy & Pivot Table (15 Marks)

print("\n" + "=" * 80)
print("TASK 8: Merge, Concatenate, GroupBy & Pivot Table")
print("=" * 80)

# Create two datasets for merging
df1 = pd.DataFrame({
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
})

df2 = pd.DataFrame({
    'Employee_ID': [101, 102, 103, 104, 105],
    'Salary': [75000, 65000, 80000, 70000, 68000],
    'Experience': [5, 3, 7, 4, 6]
})

print("\nDataFrame 1 (Employee Info):")
print(df1)
print("\nDataFrame 2 (Salary & Experience):")
print(df2)

# Merge two DataFrames using a common column
df_merged = pd.merge(df1, df2, on='Employee_ID')
print("\nMerged DataFrame (on Employee_ID):")
print(df_merged)

# Concatenate two DataFrames
df3 = pd.DataFrame({
    'Employee_ID': [106, 107],
    'Name': ['Frank', 'Grace'],
    'Department': ['IT', 'Finance']
})

df_concat = pd.concat([df1, df3], ignore_index=True)
print("\nConcatenated DataFrame:")
print(df_concat)

# GroupBy - Group data based on a selected column
print("\nGroupBy Department - Calculate aggregate values:")
grouped = df_merged.groupby('Department')

print("\nSum by Department:")
print(grouped['Salary'].sum())

print("\nMean by Department:")
print(grouped['Salary'].mean())

print("\nCount by Department:")
print(grouped['Salary'].count())

print("\nMin by Department:")
print(grouped['Salary'].min())

print("\nMax by Department:")
print(grouped['Salary'].max())

# Pivot Table
df_sales = pd.DataFrame({
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02', '2024-01-03', '2024-01-03'],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B'],
    'Sales': [1000, 1500, 1200, 1800, 1100, 1600]
})

print("\nSales DataFrame:")
print(df_sales)

# Create a Pivot Table using Pandas
pivot = pd.pivot_table(df_sales,
                       values='Sales',
                       index='Region',
                       columns='Product',
                       aggfunc='sum',
                       margins=True,
                       margins_name='Total')

print("\nPivot Table (Sales by Region and Product):")
print(pivot)




TASK 8: Merge, Concatenate, GroupBy & Pivot Table

DataFrame 1 (Employee Info):
   Employee_ID     Name Department
0          101    Alice         IT
1          102      Bob         HR
2          103  Charlie         IT
3          104    Diana    Finance
4          105      Eve         HR

DataFrame 2 (Salary & Experience):
   Employee_ID  Salary  Experience
0          101   75000           5
1          102   65000           3
2          103   80000           7
3          104   70000           4
4          105   68000           6

Merged DataFrame (on Employee_ID):
   Employee_ID     Name Department  Salary  Experience
0          101    Alice         IT   75000           5
1          102      Bob         HR   65000           3
2          103  Charlie         IT   80000           7
3          104    Diana    Finance   70000           4
4          105      Eve         HR   68000           6

Concatenated DataFrame:
   Employee_ID     Name Department
0          101    Alice         IT
1 

In [39]:
# Task 9: Exporting Data (5 Marks)

print("\n" + "=" * 80)
print("TASK 9: Exporting Data")
print("=" * 80)

# Export the final DataFrame to a new CSV file
df_merged.to_csv('processed_employees.csv', index=False)
print("\nExported merged DataFrame to: processed_employees.csv")

# Verify that the exported file contains the processed data
df_verify = pd.read_csv('processed_employees.csv')
print("\nVerification - Read back the exported file:")
print(df_verify)


TASK 9: Exporting Data

Exported merged DataFrame to: processed_employees.csv

Verification - Read back the exported file:
   Employee_ID     Name Department  Salary  Experience
0          101    Alice         IT   75000           5
1          102      Bob         HR   65000           3
2          103  Charlie         IT   80000           7
3          104    Diana    Finance   70000           4
4          105      Eve         HR   68000           6


In [40]:
# Task 10: Mini Data Analysis Project (10 Marks)

print("\n" + "=" * 80)
print("TASK 10: Mini Data Analysis Project - Sales Dataset Analysis")
print("=" * 80)

# Create a comprehensive sales dataset
sales_data = {
    'Order_ID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
                 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020],
    'Date': ['2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19',
             '2024-01-20', '2024-01-21', '2024-01-22', '2024-01-23', '2024-01-24',
             '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-28', '2024-01-29',
             '2024-01-30', '2024-01-31', '2024-02-01', '2024-02-02', '2024-02-03'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South',
               'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Laptop', 'Mouse', 'Keyboard', 'Monitor',
                'Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Laptop', 'Mouse', 'Keyboard', 'Monitor',
                'Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 'Electronics',
                 'Accessories', 'Accessories', 'Electronics', 'Electronics', 'Accessories',
                 'Accessories', 'Electronics', 'Electronics', 'Accessories', 'Accessories',
                 'Electronics', 'Electronics', 'Accessories', 'Accessories', 'Electronics'],
    'Quantity': [2, 15, 10, 5, 3, 20, 12, 6, 1, 25, 8, 4, 4, 18, 15, 7, 2, 22, 9, 5],
    'Unit_Price': [75000, 1200, 3500, 15000, 75000, 1200, 3500, 15000, 75000, 1200,
                   3500, 15000, 75000, 1200, 3500, 15000, 75000, 1200, 3500, 15000],
    'Customer_ID': ['C001', 'C002', 'C003', 'C004', 'C005', 'C006', 'C007', 'C008',
                    'C009', 'C010', 'C011', 'C012', 'C013', 'C014', 'C015', 'C016',
                    'C017', 'C018', 'C019', 'C020']
}

# Introduce some missing values for realistic scenario
sales_data['Quantity'][5] = np.nan
sales_data['Unit_Price'][12] = np.nan

df_sales_analysis = pd.DataFrame(sales_data)

print("\n1. Loading the Dataset:")
print("Dataset loaded with", len(df_sales_analysis), "rows and", len(df_sales_analysis.columns), "columns")

print("\n2. Data Inspection:")
print("\nFirst 5 rows:")
print(df_sales_analysis.head())

print("\nDataset Info:")
print(df_sales_analysis.info())

print("\n3. Identifying and Handling Missing Values:")
print("\nMissing values per column:")
print(df_sales_analysis.isnull().sum())

# Fill missing values
df_sales_analysis['Quantity'] = df_sales_analysis['Quantity'].fillna(df_sales_analysis['Quantity'].mean())
df_sales_analysis['Unit_Price'] = df_sales_analysis['Unit_Price'].fillna(df_sales_analysis['Unit_Price'].mean())

print("\nAfter filling missing values:")
print(df_sales_analysis.isnull().sum())

# Calculate Total Sales
df_sales_analysis['Total_Sales'] = df_sales_analysis['Quantity'] * df_sales_analysis['Unit_Price']

print("\n4. Selecting and Filtering Data:")
print("\nSelected columns (Order_ID, Product, Total_Sales):")
print(df_sales_analysis[['Order_ID', 'Product', 'Total_Sales']].head())

print("\nFilter: Electronics category with Total_Sales > 50000:")
print(df_sales_analysis[(df_sales_analysis['Category'] == 'Electronics') &
                        (df_sales_analysis['Total_Sales'] > 50000)])

print("\n5. Sorting Data:")
print("\nSorted by Total_Sales (Descending):")
print(df_sales_analysis.sort_values('Total_Sales', ascending=False).head())

print("\n6. Performing GroupBy Analysis:")
print("\nGroupBy Product - Total Sales:")
print(df_sales_analysis.groupby('Product')['Total_Sales'].sum())

print("\nGroupBy Region - Total Sales:")
print(df_sales_analysis.groupby('Region')['Total_Sales'].sum())

print("\nGroupBy Category - Total Sales and Average Quantity:")
print(df_sales_analysis.groupby('Category').agg({
    'Total_Sales': 'sum',
    'Quantity': 'mean'
}))

print("\n7. Creating Pivot Table:")
pivot_sales = pd.pivot_table(df_sales_analysis,
                             values='Total_Sales',
                             index='Region',
                             columns='Product',
                             aggfunc='sum',
                             margins=True,
                             margins_name='Total')

print("\nPivot Table - Total Sales by Region and Product:")
print(pivot_sales)

print("\n8. Finding Useful Insights from the Dataset:")
print("-" * 80)
print("Key Insights:")
print(f"1. Total Revenue: ₹{df_sales_analysis['Total_Sales'].sum():,.2f}")
print(f"2. Average Order Value: ₹{df_sales_analysis['Total_Sales'].mean():,.2f}")
print(f"3. Top Selling Product: {df_sales_analysis.groupby('Product')['Total_Sales'].sum().idxmax()}")
print(f"4. Top Performing Region: {df_sales_analysis.groupby('Region')['Total_Sales'].sum().idxmax()}")
print(f"5. Electronics vs Accessories Revenue:")
for category in df_sales_analysis['Category'].unique():
    revenue = df_sales_analysis[df_sales_analysis['Category'] == category]['Total_Sales'].sum()
    print(f"   - {category}: ₹{revenue:,.2f}")
print(f"6. Total Orders Processed: {len(df_sales_analysis)}")
print(f"7. Average Quantity per Order: {df_sales_analysis['Quantity'].mean():.2f}")

print("\n9. Exporting the Cleaned/Processed Dataset:")
df_sales_analysis.to_csv('processed_sales_analysis.csv', index=False)
print("Exported to: processed_sales_analysis.csv")

# Verify the exported file
df_verify_final = pd.read_csv('processed_sales_analysis.csv')
print(f"\nVerification - Exported file contains {len(df_verify_final)} rows")

print("\n" + "=" * 80)
print("ALL TASKS COMPLETED SUCCESSFULLY!")
print("=" * 80)
print("\nFiles created:")
print("1. sample_products.csv - Sample product data")
print("2. processed_employees.csv - Merged employee data")
print("3. processed_sales_analysis.csv - Final sales analysis dataset")
print("\nNote: All Python code is in this file: numpy_pandas_assignment.py")


TASK 10: Mini Data Analysis Project - Sales Dataset Analysis

1. Loading the Dataset:
Dataset loaded with 20 rows and 8 columns

2. Data Inspection:

First 5 rows:
   Order_ID        Date Region   Product     Category  Quantity  Unit_Price  \
0      1001  2024-01-15  North    Laptop  Electronics       2.0     75000.0   
1      1002  2024-01-16  South     Mouse  Accessories      15.0      1200.0   
2      1003  2024-01-17   East  Keyboard  Accessories      10.0      3500.0   
3      1004  2024-01-18   West   Monitor  Electronics       5.0     15000.0   
4      1005  2024-01-19  North    Laptop  Electronics       3.0     75000.0   

  Customer_ID  
0        C001  
1        C002  
2        C003  
3        C004  
4        C005  

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Order_ID     20 non-null     int64  
 1   Date         20 